#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     HTIRS,          sensorI2CCustom)
#pragma config(Sensor, S3,     HTGYRO,         sensorI2CCustom)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     leftTread,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightTread,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     harvester,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     leftHang,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     rightHang,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v1.h"
#include "hitechnic-gyro.h"
#include "hitechnic-accelerometer.h"
#include "hitechnic-sensormux.h"

const tSensors HTACCEL = msensor_S4_1;
const tSensors sonar = msensor_S4_2;
const tSensors color = msensor_S4_3;

typedef struct {
	TNxtButtons oldNxtButton;
	short nxtButtonChanged;

	bool mode; //false: left, true: right
	int leftSpeed;
	int rightSpeed;
	int harvesterSpeed;
	int leftHangSpeed;
	int rightHangSpeed;
} nxtState;

void initialize(nxtState *state);
void updateInput(nxtState *state);
void updateRobot(nxtState *state);
void showDiagnostics(nxtState *state);

task main()
{
	nxtState currentState;
	initialize(currentState);

	while(true){
		updateInput(currentState);
		updateRobot(currentState);
		showDiagnostics(currentState);
	}
}

void initialize(nxtState *state) {
	memset(state, 0, sizeof(state));
	state->oldNxtButton = nNxtButtonPressed;
}

void updateInput(nxtState *state) {
	state->nxtButtonChanged = state->oldNxtButton ^ nNxtButtonPressed;
	state->oldNxtButton = nNxtButtonPressed;

	if (nNxtButtonPressed == 3 && state->nxtButtonChanged)
		state->mode = !state->mode;

	if (nNxtButtonPressed == 1){
		if(state->mode)
			state->rightHangSpeed = -100;
		else
			state->leftHangSpeed = -100;
	}else if (nNxtButtonPressed == 2){
		if(state->mode)
			state->rightHangSpeed = 100;
		else
			state->leftHangSpeed = 100;
	}else {
		state->leftHangSpeed = 0;
		state->rightHangSpeed = 0;
	}
}

void updateRobot(nxtState *state) {
	motor[rightTread]=state->rightSpeed;
	motor[leftTread]=state->leftSpeed;
	motor[harvester]=state->harvesterSpeed;
	motor[leftHang]=state->leftHangSpeed;
	motor[rightHang]=state->rightHangSpeed;
}

void showDiagnostics(nxtState *state) {
	//create label
	string displayMode = "side = ";
	string batteryLevel = "power = ";

	//store variable in a string
	string string4 = state->mode?"right":"left";
	string string5 = externalBatteryAvg;

	//concat variable with label
	strcat(displayMode, string4);
	strcat(batteryLevel, string5);

	eraseDisplay();

	//display label and value
	nxtDisplayTextLine(1, "Teleop");
	nxtDisplayTextLine(2, "LftBtn:dn,RtBtn:up");
	nxtDisplayTextLine(3, "Ctr:changeSides");
	nxtDisplayTextLine(4, displayMode);
	nxtDisplayTextLine(5, batteryLevel);
}
