#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     HTIRS,          sensorI2CCustom)
#pragma config(Sensor, S3,     HTGYRO,         sensorI2CCustom)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     leftTread,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightTread,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     harvester,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     leftHang,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     rightHang,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-irseeker-v1.h"
#include "hitechnic-gyro.h"
#include "hitechnic-accelerometer.h"
#include "hitechnic-sensormux.h"

const tSensors HTACCEL = msensor_S4_1;
const tSensors sonar = msensor_S4_2;
const tSensors color = msensor_S4_3;

typedef struct {
	tButtons nxtButton;
	tButtons oldNxtButton;


	int leftSpeed;
	int rightSpeed;
	int harvesterSpeed;
	int hangSpeed;
} nxtState;

void initialize(nxtState *state);
void updateInput(nxtState *state);
void updateRobot(nxtState *state);
void stopRobot(nxtState *state);
void showDiagnostics(nxtState *state);

task main()
{
	nxtState currentState;
	initialize(currentState);

	while(true){
		updateInput(currentState);
		updateRobot(currentState);
	}
}

void initialize(nxtState *state) {
	memset(state, 0, sizeof(state));
}

void updateInput(nxtState *state) {
	if nNxtButtonPressed =
	if (abs(state->joy.joy1_y2) > 20) { // If left joystick is outside dead zone, move left tread, otherwise stop.
		state->leftSpeed = state->joy.joy1_y2 * (100.0 / 128.0) + 0.5;
	} else {
		state->leftSpeed = 0;
	}
	if (abs(state->joy.joy1_y1) > 20) { // If right joystick is outside dead zone, move right tread, otherwise stop.
		state->rightSpeed = state->joy.joy1_y1 * (100.0 / 128.0) + 0.5;
	} else {
		state->rightSpeed = 0;
	}
	if (joyButton(state->joy.joy1_Buttons, 1)) {
		state->harvesterSpeed = 100;
	} else if (joyButton(state->joy.joy1_Buttons, 2)) {
		state->harvesterSpeed = 50;
	} else {
		state->harvesterSpeed = 0;
	}
	if (joyButton(state->joy.joy1_Buttons, 3)) {
		state->hangSpeed = 100;
	} else if (joyButton(state->joy.joy1_Buttons, 4)) {
		state->hangSpeed = -100;
	} else {
		state->hangSpeed = 0;
	}
}

void updateRobot(nxtState *state) {
	motor[rightTread]=state->rightSpeed;
	motor[leftTread]=state->leftSpeed;
	motor[harvester]=state->harvesterSpeed;
	motor[leftHang]=state->hangSpeed;
	motor[rightHang]=state->hangSpeed;
}

void stopRobot(nxtState *state) {
	motor[rightTread]=0;
	motor[leftTread]=0;
	motor[harvester]=0;
	motor[leftHang]=0;
	motor[rightHang]=0;
}

void showDiagnostics(nxtState *state) {
	eraseDisplay();
	nxtDisplayTextLine(1, "TeleOp");
}
