#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     HTIRS,          sensorI2CCustom)
#pragma config(Sensor, S3,     HTGYRO,         sensorI2CCustom)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     leftTread,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightTread,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     harvester,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     leftHang,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     rightHang,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "drivers/hitechnic-sensormux.h"
#include "drivers/hitechnic-irseeker-v1.h"
#include "drivers/hitechnic-gyro.h"
#include "drivers/hitechnic-accelerometer.h"

const tMUXSensor HTACCEL = msensor_S4_1;
const tMUXSensor sonar = msensor_S4_2;
const tMUXSensor color = msensor_S4_3;

typedef struct {
	TJoystick joy;

	int leftSpeed;
	int rightSpeed;
	int harvesterSpeed;
	int leftHangSpeed;
	int rightHangSpeed;

} joyState;

void initialize(joyState *state);
void updateInput(joyState *state);
void updateRobot(joyState *state);
void showDiagnostics(joyState *state);
int joyButton(short bitmask, int button);

task main()
{
	joyState currentState;
	initialize(currentState);

	while(true){
		updateInput(currentState);
		updateRobot(currentState);
		showDiagnostics(currentState);
	}
}

void initialize(joyState *state) {
	memset(state, 0, sizeof(state));
}

void updateInput(joyState *state) {
	getJoystickSettings(joystick);
	memcpy(state->joy, joystick, sizeof(joystick));

	if (abs(state->joy.joy1_y2) > 20) { // If left joystick is outside dead zone, move left tread, otherwise stop.
		state->leftSpeed = state->joy.joy1_y2 * (100.0 / 128.0) + 0.5;
	} else {
		state->leftSpeed = 0;
	}
	if (abs(state->joy.joy1_y1) > 20) { // If right joystick is outside dead zone, move right tread, otherwise stop.
		state->rightSpeed = state->joy.joy1_y1 * (100.0 / 128.0) + 0.5;
	} else {
		state->rightSpeed = 0;
	}
	if (joyButton(state->joy.joy1_Buttons, 1)) {
		state->harvesterSpeed = 100;
	} else if (joyButton(state->joy.joy1_Buttons, 2)) {
		state->harvesterSpeed = 50;
	} else {
		state->harvesterSpeed = 0;
	}
	if (joyButton(state->joy.joy1_Buttons, 3)) {
		state->leftHangSpeed = 100;
		state->rightHangSpeed = 100;
	} else if (joyButton(state->joy.joy1_Buttons, 4)) {
		state->leftHangSpeed = -100;
		state->rightHangSpeed = -100;
	} else {
		state->leftHangSpeed = 0;
		state->rightHangSpeed = 0;
	}
}

int joyButton(short bitmask, int button)
{
	//return 1 or 0 based on whether button in bitmask is pressed or not
	return bitmask & (1 << (button - 1));
}

void updateRobot(joyState *state) {
	motor[rightTread]=state->rightSpeed;
	motor[leftTread]=state->leftSpeed;
	motor[harvester]=state->harvesterSpeed;
	motor[leftHang]=state->leftHangSpeed;
	motor[rightHang]=state->rightHangSpeed;
}

void dataLogger(){


void showDiagnostics(joyState *state) {
	//create label
	string batteryLevel = "power = ";

	//store variable in a string
	string string5 = externalBatteryAvg;

	//concat variable with label
	strcat(batteryLevel, string5);

	eraseDisplay();

	//display label and value
	nxtDisplayTextLine(3, "Teleop");
	nxtDisplayTextLine(5, batteryLevel);
}
