#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     color2,         sensorCOLORFULL)
#pragma config(Sensor, S3,     HTSPB,          sensorI2CCustom)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     leftTread,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightTread,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     flag,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     harvester,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     rightHang,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     leftHang,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    flagServo,            tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    wrist,                tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    elbow,                tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    stopper,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../headers/drivers.h"

const tMUXSensor HTIRS = msensor_S4_1;
const tMUXSensor sonar = msensor_S4_2;
const tMUXSensor color = msensor_S4_3;
const tMUXSensor HTGYRO = msensor_S4_4;

typedef struct {
	TNxtButtons oldNxtButton;
	short nxtButtonChanged;

	bool mode; //false: left, true: right
	int harvesterSpeed;
	int leftHangSpeed;
	int rightHangSpeed;
} nxtState;

void initialize(nxtState *state);
void updateInput(nxtState *state);
void updateRobot(nxtState *state);
void showDiagnostics(nxtState *state);

task main()
{
	nxtState currentState;
	initialize(currentState);

	while(true){
		updateInput(currentState);
		updateRobot(currentState);
		showDiagnostics(currentState);
	}
}

void initialize(nxtState *state) {
	memset(state, 0, sizeof(state));
	state->oldNxtButton = nNxtButtonPressed;
}

void updateInput(nxtState *state) {
	state->nxtButtonChanged = state->oldNxtButton ^ nNxtButtonPressed;
	state->oldNxtButton = nNxtButtonPressed;

	if (nNxtButtonPressed == 3 && state->nxtButtonChanged)
		state->mode = !state->mode;

	if (nNxtButtonPressed == 1){
		if(state->mode)
			state->rightHangSpeed = -100;
		else
			state->leftHangSpeed = -100;
	}else if (nNxtButtonPressed == 2){
		if(state->mode)
			state->rightHangSpeed = 100;
		else
			state->leftHangSpeed = 100;
	}else {
		state->leftHangSpeed = 0;
		state->rightHangSpeed = 0;
	}
}

void updateRobot(nxtState *state) {
	motor[harvester]=state->harvesterSpeed;
	motor[leftHang]=state->leftHangSpeed;
	motor[rightHang]=state->rightHangSpeed;
}

void showDiagnostics(nxtState *state) {
	//create label
	string displayMode = "side = ";
	string batteryLevel = "power = ";

	//store variable in a string
	string string4 = state->mode?"right":"left";
	string string5 = externalBatteryAvg;

	//concat variable with label
	strcat(displayMode, string4);
	strcat(batteryLevel, string5);

	eraseDisplay();

	//display label and value
	nxtDisplayTextLine(1, "HangLowerer");
	nxtDisplayTextLine(2, "LftBtn:dn,RtBtn:up");
	nxtDisplayTextLine(3, "Ctr:changeSides");
	nxtDisplayTextLine(4, displayMode);
	nxtDisplayTextLine(5, batteryLevel);
}
